### ISSUE TITLE
Flakey test in strategies_controller_spec.rb related to `ActiveRecord::RecordNotUnique`

### ISSUE THREAD

**Issue by julianguyen** [ifmeorg/ifme#1144]
# Description 

I notice this is a frequent flakey test that fails on CircleCI. Sometimes I see it happen randomly when I run rspec in my dev environment. Maybe there's a race condition happening? O.o

```
spec/controllers/strategies_controller_spec.rb
Failure/Error: another_user = create(:user)

ActiveRecord::RecordNotUnique:
  PG::UniqueViolation: ERROR:  duplicate key value violates unique constraint "users_pkey"
  DETAIL:  Key (id)=(1) already exists.
  : INSERT INTO "users" ("email", "encrypted_password", "created_at", "updated_at", "name", "uid") VALUES ($1, $2, $3, $4, $5, $6) RETURNING "id"
./spec/controllers/strategies_controller_spec.rb:298:in `block (5 levels) in <top (required)>'
------------------
--- Caused by: ---
PG::UniqueViolation:
  ERROR:  duplicate key value violates unique constraint "users_pkey"
  DETAIL:  Key (id)=(1) already exists.
  ./spec/controllers/strategies_controller_spec.rb:298:in `block (5 levels) in <top (required)>'
```

# Do you want to be the assignee to work on this?

🚫

**Comment by jaimevelaz** [comment]
I can take a look at this one 😁
